framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    handle_all_throwables: true
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for']
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    http_method_override: true

when@dev:
    framework:
        profiler:
            collect: true
            collect_serializer_data: true
