twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'

when@dev:
    twig:
        debug: true
        strict_variables: true

when@test:
    twig:
        strict_variables: true
